### ISSUE TITLE
KVM shows connected, but the screen is blank. 

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/console#191]
Acceptance Criteria

- [ ] Update URL to allow different structure
- [ ] Update Web UI Toolkit to handle different structure
- [ ] Update URL to respect TLS selection on the device when configured.

It just sits at this blank screen, 10 minutes now. This is an AMT 16.1.27 system. I also tried changing to RLE16. Then tried Mesh Commander and it can connect. 

![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/7d49f8fd-2200-4756-b5ba-a5a335977fbc)

![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/50369620-0e5a-40d8-8561-d7a3c3c240f9)

**Comment by mtpham-1** [comment]
KVM connection is unreliable, now my other systems cannot connect even though the KVM says it’s connected.

![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/46225ecf-72be-4506-8118-fbed818cf1e5)

**Comment by bwendlandt-intel** [comment]
Additional info:
Known issue for >=16.1 devices.  Current KVM connection implementation uses 16994. To support TLS, need to enable use of 16995 for TLS devices.

**Comment by rsdmike** [comment]
This was fixed with https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/361
