### ISSUE TITLE
Once connected to KVM, there are no options buttons to do any AMT operations such as reboot, reset, KVM, resent to bios, etc

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/console#195]
![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/6ea846d7-1c08-4fc7-8390-eda63936b7a0)

Reproduce steps…

![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/02dcd0a3-d9b1-44c7-affc-2d3bd6b7a95d)

**Comment by bwendlandt-intel** [comment]
For cause, solution, and tracking of a fix see: https://github.com/open-amt-cloud-toolkit/console/issues/194
