### ISSUE TITLE
Once connected via SOL, there are no options/buttons to do any AMT actions.

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/console#196]
![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/e4dce623-0b6f-4b35-92d1-f13ff7d487c5)

Reproduce steps…

Click the SOL button

![image](https://github.com/open-amt-cloud-toolkit/console/assets/140858054/f3bf67ec-5e9f-4a86-9ec7-863712fb5cfa)

**Comment by bwendlandt-intel** [comment]
For cause, solution, and tracking of a fix see: https://github.com/open-amt-cloud-toolkit/console/issues/194
