### ISSUE TITLE
v1.0.0-alpha.8: Clicking the check box next to a system and Action items disappear.

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/console#284]
**Describe the bug**
In the devices menu, putting a check in the box causes the Action items to disappear. Seeing this behavior on console version 1.0.0-alpha.8

**Screenshots**

![image](https://github.com/user-attachments/assets/c57e3027-ab8b-49fd-9b23-5d779715b940)

**Comment by rsdmike** [comment]
This is by design. When selecting multiple devices, use the row of a single device to affect multiple does not makes sense. The actions move above and are hidden for this reason.
