### ISSUE TITLE
AMT Features response says Undefined when saved/updated

### ISSUE THREAD

**Issue by graikhel-intel** [open-amt-cloud-toolkit/console#297]
**Describe the bug**
AMT Features response says Undefined when saved/updated.

**To Reproduce**
1. Connect to a device
2. Enable or Disable one of the AMT features (Ex: KVM)
3. See the error `UNDEFINED` at the bottom of the screen

**Screenshots**
![image](https://github.com/user-attachments/assets/7c792bec-432b-4c0e-a1d9-ff56daf95324)

**Comment by mechris1** [comment]
Design a fix for all  situations but only implement for this scenario.
